### PR TITLE
Prevent data conflicts across multiple versions

### LINKED ISSUE #4: loading multiple versions overriding each other
If I do this:
```
const Block1_12 = require("prismarine-block")("1.12");
const Block1_13 = require("prismarine-block")("1.13.2");
const Block1_14 = require("prismarine-block")("1.14.4");
```
and try to instantiate a `Block1_12` it will fail since the 1.14 imlp. doesn't ship block data.

https://github.com/PrismarineJS/prismarine-block/blob/master/index.js#L6

### PR DESCRIPTION
**Pull request by hornta**
Fixes #4

### CODE REVIEW

**Comment by rom1504** [comment]
Makes sense.
We need the same pr basically everywhere then if we want to support importing multiple version at once then though

**Comment by hornta** [comment]
Yes, I came across the same problem in flying-squid with the portal detector:
https://github.com/PrismarineJS/flying-squid/blob/master/src/lib/portal_detector.js#L125
see "Chunk"

**Comment by hornta** [comment]
I'm pretty sure it's only a problem during testsruns but better to be safe than sorry

**Comment by rom1504** [comment]
Ah tests. Good point.
Then yeah we need to do the same change everywhere.

Maybe you could do it ?
It needs to be done in all the prismarine-*, in mineflayer and flying-squid

**Comment by hornta** [comment]
I can do that when time comes. It would be nice if all prismarine packages could be put in one repo to ease things like this. I know a great tool called Lerna for having multi npm package in the same repo, like for example React does. I think it would be very cool to have the prismarine-* in the same repo

**Comment by rom1504** [comment]
I don't think a monorepo is a good thing in this case.
A monorepo is useful when you have package that are tightly coupled.
That's not really the case here.
I'm trying to keep a coherence between them in term of technical choices
but besides that these packages are completely independent

**Pull request merged**
